- name: Ensure we have a directory for nginx configs & static data
  file:
    path: '{{ gb_root }}/volumes/nginx/static'
    state: directory
- name: Copy over basic landing page
  copy:
    src: lander.html
    dest: '{{ gb_root }}/volumes/nginx/static/index.html'
- name: Copy over static files for landing page
  copy:
    src: gorilla_tile.png
    dest: '{{ gb_root }}/volumes/nginx/static/gorilla_tile.png'
- name: Copy over base nginx config (non-SSL)
  when: not gb_enable_ssl
  copy:
    src: base.conf
    dest: '{{ gb_root }}/volumes/nginx/nginx.conf'
- name: Write base nginx config from template (SSL)
  when: gb_enable_ssl
  template:
    src: base.ssl.conf.j2
    dest: '{{ gb_root }}/volumes/nginx/nginx.conf'
- name: Copy over proxy config files for the services
  copy:
    src: services
    dest: '{{ gb_root }}/volumes/nginx'
