filebrowser:
  image: filebrowser/filebrowser:latest
  user: "{{ user_uid.stdout }}:{{ user_gid.stdout }}"
  volumes:
    - "{{ filebrowser_root_path }}:/srv"
    - "./data/filebrowser/database.db:/database.db"
    - "./data/filebrowser/filebrowser.json:/.filebrowser.json"
  ports:
    - "8080:8080"
  restart: always
