auth:
  - user: ${SAMBA_USERNAME}
    group: ${SAMBA_USERNAME}
    uid: ${GB_USER_UID}
    gid: ${GB_USER_GID}
    password: "${SAMBA_PASSWORD}"

share:
  - name: ghettobox
    path: /samba/ghettobox
    browsable: yes
    readonly: no
    guestok: no
    veto: no
    validusers: ${SAMBA_USERNAME}
    writelist: ${SAMBA_USERNAME}
