navidrome:
  image: deluan/navidrome:latest
  user: "{{ gb_user_uid }}:{{ gb_user_gid }}"
  ports:
    - "4533:4533"
  environment:
    ND_CONFIGFILE: "/data/config.toml"
  volumes:
    - "./data/navidrome:/data"
    - "{{ navidrome_music_path }}:/music:ro"
  restart: always
