reverseproxy:
  image: nginx
  volumes:
    - ./nginx/ssl:/etc/nginx/ssl
    - ./nginx/services:/etc/nginx/conf.d/services
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  network_mode: host
  restart: always
