- name: Ensure our user owns transmission's downloads share
  file:
    path: '{{ transmission_share_path }}'
    owner: '{{ ansible_ssh_user }}'
    recurse: true
    state: directory
  become: true

- name: Ensure we have directories for transmission's config/torrents
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ gb_root }}/volumes/transmission/config'
    - '{{ gb_root }}/volumes/transmission/watch'
