- name: Ensure our user owns transmission's downloads share
  file:
    path: '{{ transmission_share_path }}'
    owner: '{{ ansible_ssh_user }}'
    recurse: true
    state: directory
  become: true

- name: Ensure we have a directory for transmission's config 
  file:
    path: '{{ gb_root }}/volumes/transmission/config'
    state: directory
