- name: Copy over launcher script
  copy:
    src: launcher.sh
    dest: '{{ gb_root }}/launcher.sh'
    mode: u+x

- name: Ensure ansible_ssh_user recursively owns everything placed in gb_root
  file:
    path: '{{ gb_root }}'
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    recurse: true
  become: true

- name: Create populated docker-compose.yml file for service initialization
  template:
    src: templates/docker-compose.yml.j2
    dest: '{{ gb_root }}/docker-compose.yml'
