- name: Copy over launcher script
  copy:
    src: launcher.sh
    dest: '{{ gb_root }}/launcher.sh'
    mode: u+x

- name: Create populated docker-compose.yml file for service initialization
  template:
    src: templates/docker-compose.yml
    dest: '{{ gb_root }}/docker-compose.yml'

- name: Ensure only provisioning user can read/write docker-compose.yml
  file:
    path: '{{ gb_root }}/docker-compose.yml'
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '600'

