tasks:
  - name: Copy over launcher script
    copy:
      src: launcher.sh
      dest: "{{ gb_root }}/launcher.sh"
      mode: u+x

  - name: Create populated docker-compose.yml file for service initialization
    template:
      src: templates/docker-compose.yml.j2
      dest: "{{ gb_root }}/docker-compose.yml"
