tasks:
  - name: Copy over launcher script
    copy:
      src: launcher.sh
      dest: "{{ gb_root }}/launcher.sh"
      mode: u+x

  - name: Ensure gb_user owns everything placed in gb_root
    file:
      path: "{{ gb_root }}"
      state: directory
      owner: "{{ gb_user }}"
      recurse: yes
    become: yes

  - name: Create populated docker-compose.yml file for service initialization
    template:
      src: templates/docker-compose.yml.j2
      dest: "{{ gb_root }}/docker-compose.yml"
