compose:
  watchtower:
    image: containrrr/watchtower
    environment:
      TZ: "{{ local_timezone }}"
    command: >
      --schedule "0 0 4 */14 * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
