compose:
  watchtower:
    image: containrrr/watchtower
    environment:
      TZ: "{{ local_timezone }}"
    command: >
      --schedule "{{ watchtower_schedule }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
