#!/bin/bash
export GB_USER_UID="$(id -u)"
export GB_USER_GID="$(id -g)"
export SAMBA_USERNAME=""
export SAMBA_PASSWORD=""
export OPENVPN_USERNAME=""
export OPENVPN_PASSWORD=""
export OPENVPN_SERVER_REGIONS=""
export TRANSMISSION_USERNAME=""
export TRANSMISSION_PASSWORD=""
export SOULSEEK_USERNAME=""
export SOULSEEK_PASSWORD=""
export SLSKD_USERNAME=""
export SLSKD_PASSWORD=""
export COUCHDB_USER=""
export COUCHDB_PASSWORD=""
export VIKUNJA_SERVICE_JWTSECRET="refresco-cont-net"
export VIKUNJA_SERVICE_PUBLICURL="http://localhost:3456"

docker compose "$@"
