- hosts: gb_host
  roles:
  - setup         # setup tasks - don't comment/disable this role
  - firewall      # configure UFW, only allowing 22 from LAN, 443 from anywhere 
  - filebrowser   # web-based file manager for a specified volume
  - navidrome     # self-hosted spotify
  - jellyfin      # self-hosted netflix
  - kavita        # read manga and comics
  - samba         # share a volume over a network
  - slskd         # limewire for a new generation
  - restic        # automatic backups for a specified volume
  - transmission  # server-hosted bittorrent session behind VPN
  - caddy         # reverse proxy for accessing other services
  - baikal        # calDAV service for self-hosted calendar
  - finalize      # final tasks - don't comment/disable this role either
